// 1bpp bitmap font format shared by the device firmware and the host simulator.
//
// Glyph bitmaps are packed 1 bit per pixel, MSB first, rows packed continuously
// (no per-row byte padding) -- the same layout Adafruit_GFX uses, so existing
// font converters are easy to adapt. Headers under fonts/ are generated by
// tools/genfont.py.
#pragma once

#include <stdint.h>

// ESP32 flash is memory mapped, so const data is directly addressable and no
// pgm_read_* accessors are needed. The hook is kept for AVR-style targets.
#ifndef TI_PROGMEM
#define TI_PROGMEM
#endif

struct TiGlyph {
    uint32_t bitmapOffset;  // byte offset into the font's bitmap blob
    uint8_t width;          // glyph bounding box, pixels
    uint8_t height;
    uint8_t xAdvance;  // pen movement after drawing this glyph
    int8_t xOffset;    // left edge relative to the pen position
    int8_t yOffset;    // top edge relative to the baseline (negative = above)
};

struct TiFont {
    const uint8_t* bitmap;
    const TiGlyph* glyph;
    uint8_t first;       // first character code present
    uint8_t last;        // last character code present
    uint8_t lineHeight;  // ascent + descent, pixels
    uint8_t ascent;      // baseline offset from the top of the line box
};
