#include "iwls_client.h"

#include <HTTPClient.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <esp_sntp.h>
#include <time.h>

#include "config.h"
#include "iwls_parse.h"
#include "secrets.h"

namespace {

const char* kApiHost = "https://api-iwls.dfo-mpo.gc.ca";
const char* kApiPath = "/api/v1";

// The Mozilla root store generated by ESP-IDF and linked into the mbedTLS
// library that ships with the Arduino framework. Referencing the symbol is what
// pulls the ~64 kB blob into the image.
extern "C" const uint8_t kRootCaBundle[] asm("_binary_x509_crt_bundle_start");

// The parsed download lands here first so a half-finished refresh cannot
// corrupt the cached predictions. Static rather than stack: it is ~1.2 kB.
TideData g_incoming;

// Anything before this is a clock that has never been set.
const int64_t kPlausibleEpoch = 1700000000;

// Set from the SNTP callback when a response actually lands.
volatile bool g_clockSynced = false;

void onTimeSync(struct timeval*) { g_clockSynced = true; }

void formatUtc(int64_t epoch, char* out, size_t n) {
    const time_t t = (time_t)epoch;
    struct tm tm;
    gmtime_r(&t, &tm);
    strftime(out, n, "%Y-%m-%dT%H:%M:%SZ", &tm);
}

bool connectWifi() {
    if (WiFi.status() == WL_CONNECTED) return true;
    WiFi.persistent(false);
    WiFi.mode(WIFI_STA);
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    const uint32_t deadline = millis() + WIFI_TIMEOUT_MS;
    while (WiFi.status() != WL_CONNECTED && millis() < deadline) {
        delay(150);
    }
    if (WiFi.status() != WL_CONNECTED) {
        Serial.println("[net] Wi-Fi connect failed");
        return false;
    }
    Serial.printf("[net] connected, %d dBm, ip %s\n", WiFi.RSSI(),
                  WiFi.localIP().toString().c_str());
    return true;
}

void stopWifi() {
    WiFi.disconnect(true, true);
    WiFi.mode(WIFI_OFF);
}

bool syncClock() {
    // The RTC runs off the C3's internal RC oscillator (no 32.768 kHz crystal on
    // this board), which drifts by minutes a day and is temperature-sensitive,
    // so the clock has to be pulled back to NTP on every refresh -- not just on
    // the first boot.
    //
    // configTzTime() only *starts* the SNTP client; it does not block. Waiting
    // on "is the clock plausible" would return instantly on every boot after the
    // first and leave the correction to whether a packet happened to arrive
    // before the radio went down, so wait on the sync notification itself.
    g_clockSynced = false;
    sntp_set_sync_mode(SNTP_SYNC_MODE_IMMED);
    sntp_set_time_sync_notification_cb(onTimeSync);
    configTzTime(LOCAL_TZ, NTP_SERVER_1, NTP_SERVER_2);

    const int64_t before = (int64_t)time(nullptr);
    const uint32_t deadline = millis() + NTP_TIMEOUT_MS;
    while (!g_clockSynced && millis() < deadline) {
        delay(50);
    }

    if (!g_clockSynced) {
        // An already-set clock is still usable, just drifting: carry on with the
        // download rather than throwing the whole refresh away over a slow NTP
        // server. Only a clock that was never set is fatal.
        const bool set = (int64_t)time(nullptr) > kPlausibleEpoch;
        Serial.printf("[net] NTP sync failed (clock %s)\n", set ? "set, drifting" : "unset");
        return set;
    }

    Serial.printf("[net] clock synced, drift was %+lld s\n",
                  (long long)((int64_t)time(nullptr) - before));
    return true;
}

// Both downloads go to the same host, one straight after the other, so they can
// share a single TLS session. After the Wi-Fi association, the handshake is the
// most expensive thing in a refresh -- certificate chain verification against
// the root bundle is seconds of radio and CPU -- and the old code paid for two
// of them by building a fresh WiFiClientSecure per request and turning reuse
// off. The IWLS API answers on HTTP/1.1 with Connection: keep-alive, so the
// second request can ride the first handshake.
//
// The mechanics are particular. HTTPClient keeps the socket open after
// getString() only while setReuse() is on -- which is its default, and which the
// old code was explicitly switching off -- and the follow-up request has to
// arrive through setURL() with a *path*, not a fresh begin(): a path-only
// setURL() swaps the URI and leaves the host, the port and the open socket
// alone.
struct ApiSession {
    WiFiClientSecure client;
    HTTPClient http;
    bool connected = false;

    // GETs `path` (with a leading slash), opening a connection if there is none.
    bool get(const char* path, String& body);
    void close();

   private:
    bool attempt(const char* path, String& body);
};

bool ApiSession::attempt(const char* path, String& body) {
    if (!connected) {
        client.setCACertBundle(kRootCaBundle);
        client.setTimeout(HTTP_TIMEOUT_MS / 1000);
        http.setTimeout(HTTP_TIMEOUT_MS);
        // The default, stated for the reader: it is what keeps the socket alive
        // between the two downloads.
        http.setReuse(true);
        char url[320];
        snprintf(url, sizeof(url), "%s%s", kApiHost, path);
        if (!http.begin(client, url)) {
            Serial.println("[http] begin failed");
            return false;
        }
        connected = true;
    } else if (!http.setURL(path)) {
        Serial.println("[http] setURL failed");
        return false;
    }

    const int code = http.GET();
    if (code != HTTP_CODE_OK) {
        Serial.printf("[http] %s -> %d\n", path, code);
        // A rejected certificate looks like a plain connection failure at the
        // HTTPClient level, so ask the TLS layer what really went wrong.
        char reason[128] = {0};
        if (client.lastError(reason, sizeof(reason)) != 0) Serial.printf("[tls] %s\n", reason);
        return false;
    }
    body = http.getString();
    Serial.printf("[http] %d bytes\n", body.length());
    return body.length() > 2;
}

bool ApiSession::get(const char* path, String& body) {
    const bool reusing = connected;
    if (attempt(path, body)) return true;
    // A socket the server closed between our two requests fails at the transport
    // layer rather than with a status code, and there is no way to tell that
    // apart from a real failure without trying. So spend the handshake once --
    // which lands exactly where the old request-per-connection code started from
    // every single time -- and only then give up.
    if (!reusing) return false;
    Serial.println("[http] reused connection failed, retrying on a fresh one");
    close();
    return attempt(path, body);
}

void ApiSession::close() {
    if (!connected) return;
    // Without this end() politely holds the socket open for a request that is
    // not coming, and the radio goes down underneath it.
    http.setReuse(false);
    http.end();
    client.stop();
    connected = false;
}

bool fetchSeries(ApiSession& api, int64_t now, const char* series, int hoursBefore,
                 int hoursAfter, const char* resolution, String& body) {
    char from[32], to[32];
    formatUtc(now - (int64_t)hoursBefore * 3600, from, sizeof(from));
    formatUtc(now + (int64_t)hoursAfter * 3600, to, sizeof(to));

    // A path rather than a full URL, because that is what lets the second call
    // reuse the first call's connection. See ApiSession.
    char path[320];
    snprintf(path, sizeof(path), "%s/stations/%s/data?time-series-code=%s&from=%s&to=%s%s%s",
             kApiPath, IWLS_STATION_ID, series, from, to, resolution ? "&resolution=" : "",
             resolution ? resolution : "");
    return api.get(path, body);
}

}  // namespace

const char* fetchStatusMessage(FetchStatus status) {
    switch (status) {
        case FetchStatus::kOk:
            return "";
        case FetchStatus::kWifiFailed:
            return "WI-FI UNREACHABLE - SHOWING CACHED PREDICTIONS";
        case FetchStatus::kClockFailed:
            return "CLOCK NOT SET - COULD NOT REACH A TIME SERVER";
        case FetchStatus::kHttpFailed:
            return "TIDE SERVICE UNREACHABLE - SHOWING CACHED PREDICTIONS";
        case FetchStatus::kParseFailed:
            return "UNEXPECTED RESPONSE FROM THE TIDE SERVICE";
    }
    return "";
}

FetchStatus iwlsRefresh(TideData& data) {
    if (!connectWifi()) {
        stopWifi();
        return FetchStatus::kWifiFailed;
    }
    if (!syncClock()) {
        stopWifi();
        return FetchStatus::kClockFailed;
    }

    const int64_t now = (int64_t)time(nullptr);
    tideDataReset(g_incoming);
    snprintf(g_incoming.stationName, sizeof(g_incoming.stationName), "%s", STATION_DISPLAY_NAME);

    FetchStatus status = FetchStatus::kOk;
    // One session for both series: the second download rides the first
    // handshake. Scoped so the socket is shut before the radio goes down.
    {
        ApiSession api;
        {
            String body;
            if (!fetchSeries(api, now, "wlp-hilo", HILO_HOURS_BEFORE, HILO_HOURS_AFTER, nullptr,
                             body)) {
                status = FetchStatus::kHttpFailed;
            } else if (!iwlsParseHiLo(body.c_str(), body.length(), g_incoming)) {
                status = FetchStatus::kParseFailed;
            }
        }
        if (status == FetchStatus::kOk) {
            String body;
            if (!fetchSeries(api, now, "wlp", CURVE_HOURS_BEFORE, CURVE_HOURS_AFTER,
                             CURVE_RESOLUTION, body)) {
                status = FetchStatus::kHttpFailed;
            } else if (!iwlsParseCurve(body.c_str(), body.length(), g_incoming)) {
                status = FetchStatus::kParseFailed;
            }
        }
        api.close();
    }
    stopWifi();

    if (status != FetchStatus::kOk) return status;

    g_incoming.fetchedAt = now;
    g_incoming.valid = true;
    data = g_incoming;
    Serial.printf("[iwls] %u extremes, %u curve points at %us spacing\n", data.extremeCount,
                  data.curve.count, data.curve.stepSec);
    return FetchStatus::kOk;
}
