#!/usr/bin/env python3
"""Generate 1bpp bitmap font headers for the tide clock UI.

The output format matches the layout used by Adafruit_GFX (glyph bitmaps are
packed 1 bit per pixel, MSB first, with no per-row padding) but uses our own
`TiFont` / `TiGlyph` structs so that the renderer is identical on the ESP32-C3
and in the host simulator.

Source faces are DejaVu (Bitstream Vera / DejaVu license -- redistributable and
compatible with this project's MIT license). Generated headers are committed, so
this script only needs to be re-run when the font set changes:

    python3 tools/genfont.py

Requires Pillow (`pip install pillow`) and the DejaVu TTFs.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass

try:
    from PIL import ImageFont
except ImportError:  # pragma: no cover - developer tooling
    sys.exit("Pillow is required: pip install pillow")

FONT_DIRS = [
    "/usr/share/fonts/truetype/dejavu",
    "/usr/share/fonts/dejavu",
    "/usr/local/share/fonts/dejavu",
    "/Library/Fonts",
    "/opt/homebrew/share/fonts",
    os.path.expanduser("~/.fonts"),
]

FIRST_CHAR = 0x20  # space
LAST_CHAR = 0x7E  # tilde

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "lib", "tideui", "src", "fonts")


@dataclass
class FontSpec:
    name: str  # C identifier, e.g. FontBig
    ttf: str  # file name of the source face
    size: int  # pixel size passed to FreeType


FONTS = [
    FontSpec("FontBig", "DejaVuSans-Bold.ttf", 58),
    FontSpec("FontH1", "DejaVuSans-Bold.ttf", 30),
    FontSpec("FontH2", "DejaVuSans-Bold.ttf", 20),
    FontSpec("FontBody", "DejaVuSans.ttf", 18),
    FontSpec("FontLabel", "DejaVuSans-Bold.ttf", 14),
    FontSpec("FontTiny", "DejaVuSans.ttf", 13),
]


def find_ttf(name: str) -> str:
    for d in FONT_DIRS:
        p = os.path.join(d, name)
        if os.path.isfile(p):
            return p
    sys.exit(
        f"Could not find {name}. Install the DejaVu fonts (Debian/Ubuntu: "
        f"`apt-get install fonts-dejavu-core`) or add the directory to FONT_DIRS."
    )


def render_glyph(font: ImageFont.FreeTypeFont, ch: str):
    """Return (width, height, xoff, yoff_from_baseline, xadvance, packed_bits)."""
    mask, offset = font.getmask2(ch, mode="1")
    w, h = mask.size
    ascent, _descent = font.getmetrics()
    xoff, yoff = offset[0], offset[1] - ascent
    advance = int(round(font.getlength(ch)))

    bits = bytearray()
    acc = 0
    nbits = 0
    for y in range(h):
        for x in range(w):
            acc = (acc << 1) | (1 if mask.getpixel((x, y)) else 0)
            nbits += 1
            if nbits == 8:
                bits.append(acc)
                acc, nbits = 0, 0
    if nbits:
        bits.append(acc << (8 - nbits))
    return w, h, xoff, yoff, advance, bytes(bits)


def emit(spec: FontSpec) -> str:
    path = find_ttf(spec.ttf)
    font = ImageFont.truetype(path, spec.size)
    ascent, descent = font.getmetrics()

    bitmap = bytearray()
    glyphs = []
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        ch = chr(code)
        w, h, xoff, yoff, adv, bits = render_glyph(font, ch)
        if w == 0 or h == 0:  # space and friends
            w = h = 0
            xoff = yoff = 0
            bits = b""
        glyphs.append((len(bitmap), w, h, adv, xoff, yoff, ch))
        bitmap.extend(bits)

    lines = []
    lines.append(f"// Generated by tools/genfont.py -- do not edit by hand.")
    lines.append(f"// Source: {spec.ttf} @ {spec.size}px (DejaVu / Bitstream Vera license)")
    lines.append("#pragma once")
    lines.append("")
    lines.append('#include "../font.h"')
    lines.append("")
    lines.append(f"static const uint8_t {spec.name}Bitmaps[] TI_PROGMEM = {{")
    for i in range(0, len(bitmap), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in bitmap[i : i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    lines.append(f"static const TiGlyph {spec.name}Glyphs[] TI_PROGMEM = {{")
    for off, w, h, adv, xoff, yoff, ch in glyphs:
        label = "space" if ch == " " else ch
        lines.append(
            f"    {{ {off}, {w}, {h}, {adv}, {xoff}, {yoff} }},  // '{label}'"
        )
    lines.append("};")
    lines.append("")
    lines.append(f"static const TiFont {spec.name} TI_PROGMEM = {{")
    lines.append(f"    {spec.name}Bitmaps,")
    lines.append(f"    {spec.name}Glyphs,")
    lines.append(f"    0x{FIRST_CHAR:02X}, 0x{LAST_CHAR:02X},")
    lines.append(f"    {ascent + descent},  // line height")
    lines.append(f"    {ascent},  // ascent")
    lines.append("};")
    lines.append("")

    out = os.path.normpath(os.path.join(OUT_DIR, f"{spec.name.lower()}.h"))
    with open(out, "w") as f:
        f.write("\n".join(lines))
    return f"{out}: {len(bitmap)} bytes of glyph data, line height {ascent + descent}px"


def main() -> None:
    os.makedirs(os.path.normpath(OUT_DIR), exist_ok=True)
    for spec in FONTS:
        print(emit(spec))

    index = os.path.normpath(os.path.join(OUT_DIR, "fonts.h"))
    with open(index, "w") as f:
        f.write("// Generated by tools/genfont.py -- do not edit by hand.\n")
        f.write("#pragma once\n\n")
        for spec in FONTS:
            f.write(f'#include "{spec.name.lower()}.h"\n')
    print(index)


if __name__ == "__main__":
    main()
